name = "Kiss"
license = "MIT"
licenselink = "https://github.com/ribice/kiss/master/LICENSE.md"
description = "Stupidly simple Hugo blogging theme"
homepage = "https://www.ribice.ba/hugo-kiss/"
tags = [
  "blog",
  "minimal",
  "minimalist",
  "responsive"
]
features = [
  "accessibility",
  "analytics",
  "cover-image",
  "favicon",
  "multilingual",
  "opengraph",
  "pagination",
  "shortcodes",
  "single-column",
  "social-menu",
  "syntax-highlighting",
]
min_version = 0.28

[author]
  name = "evan"
  homepage = "https://evanlau.me"

[original]
  name = "ribice"
  homepage = "https://ribice.ba"
  repo = "https://github.com/ribice/kiss"
