baseurl = "https://www.example.com"
languageCode = "en"
title = "Hugo Kiss theme"
theme = "kiss"
copyright = "2018 &copy; Evan Lau"

# Number of posts per page
Paginate = 10
enableRobotsTXT = true

[params.assets]
customCSS = ["css/custom.css"]

[params.info]
enableSocial = false # Adds OpenGraph and Twitter cards
homeTitle = "" # Title for home page
poweredby = true # Adds powered by Hugo and Kiss below Copyright section
related = true # Includes related articles

[params.opengraph.facebook]
admins = [] # array of Facebook IDs
appID = ""
pageID = ""

[params.opengraph.twitter]
page = "" # Twitter Page username. If not set, params.social.twitter will be used.

[params.social]

twitter = "twitter"
github = "github"
email = "hi@email.com"
linkedin = "linkedin"
facebook = "facebook"
instagram = "instagram"
codepen = "codepen"
telegram = "telegram"
gitlab = "gitlab"

[params.matomoAnalytics]
siteID = 1
rootURL = "//matomo.example.com/"

[taxonomies]
tag ="tags"

[blackfriday]
hrefTargetBlank = true

